
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/classic:201708-01
    working_directory: ~/repo

    steps:
      - checkout
      - run: echo 'deploying master branch'
      - run: sh ./deploy.sh
      - run: |
          scp -r ./dist/* $DROPLET_USER@DROPLET_IP:/var/www/html/dist/