version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP; cd /var/www/html; git pull; npm run build
       - run: cd /var/www/html
       - run: git pull
       - run: npm install
       - run: npm run build