version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP; cd /var/www/html; git pull; npm run build