
machine:
  services:
    - docker

deployment:
  master:
    branch: master
    commands:
      - echo 'deploying'
      - ssh -v $DROPLET_USER@$DROPLET_IP "cd /var/www/html; sh ./deploycircle_deployer.sh"