version: 2
jobs:
   build:
     machine: true
     steps:
       - checkout
       - deploy:
            name: Deploy to VPS 
            command: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP "cd /var/www/html; git pull; npm install; npm run build"